unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim
set termguicolors

let mapleader = "\<space>"

set noswapfile
set viminfo+=n~/.vim/viminfo

call plug#begin('$HOME/.vim/vendor')

Plug '~/vimming/zenbones.nvim'
Plug '~/vimming/nnn.vim'

call plug#end()
