unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

let mapleader = "\<space>"

set noswapfile
set viminfo+=n~/.vim/viminfo

let g:nnn#layout = #{ window: #{ width: 0.9, height: 0.6 } }

call plug#begin('$HOME/.vim/vendor')

Plug '~/vimming/nnn.vim'
Plug '~/vimming/zenbones.nvim'
Plug 'lifepillar/vim-gruvbox8'

call plug#end()

let &t_ZH="\e[3m"
let &t_ZR="\e[23m"

set laststatus=2
set termguicolors
set background=dark
colorscheme tokyobones
let g:gruvbox_italics = 1
" colorscheme gruvbox8
